trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Fetch SDK 6.0.x'
  inputs:
    version: '6.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: |
      **/*.csproj
      !**/*.Tests.csproj
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '**/*[Tt]est*/*.csproj'
    publishTestResults: true
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage results'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/*coverage.cobertura.xml'

#- task: DotNetCoreCLI@2
#  displayName: 'dotnet test'
#  inputs:
#    command: 'test'
#    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
#    publishTestResults: true
#    projects: '**/*.Tests/*.csproj'
#  
#- task: PublishCodeCoverageResults@1
#  displayName: 'Publish code coverage report'
#  inputs:
#    codeCoverageTool: 'Cobertura'
#    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'publishing artifact'