# a basic pipeline to test if the build is successful after merge

trigger:
- none

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Fetch SDK 6.0.x'
  inputs:
    version: '6.0.x'
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudSC'
    organization: 'endavasfd'
    scannerMode: 'MSBuild'
    projectKey: 'EndavaSfd_elephants-internary-api'
    projectName: 'elephants-internary-api'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: |
      **/*.csproj
      !**/*.Tests.csproj
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: '**/*.Tests/*.csproj'
    publishTestResults: false
    arguments: '--configuration $(buildConfiguration) --logger trx --results-directory "$(Agent.TempDirectory)" --collect "Code coverage"'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '*.trx'
    searchFolder: '$(Agent.TempDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True