// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(InternaryContext))]
    [Migration("20220920125917_InternsFeature")]
    partial class InternsFeature
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Features.Campaigns.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Core.Features.Interns.Entities.Intern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interns");
                });

            modelBuilder.Entity("Core.Features.Interns.Entities.InternCampaign", b =>
                {
                    b.Property<Guid>("InternId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecialityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InternId", "CampaignId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("InternCampaigns");
                });

            modelBuilder.Entity("Core.Features.Interns.Entities.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InternId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("InternId", "CampaignId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("Core.Features.Interns.Entities.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            StatusId = 0,
                            Name = "Candidate"
                        },
                        new
                        {
                            StatusId = 1,
                            Name = "Intern"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "Rejected"
                        },
                        new
                        {
                            StatusId = 3,
                            Name = "RejectedToStart"
                        },
                        new
                        {
                            StatusId = 4,
                            Name = "Hired"
                        });
                });

            modelBuilder.Entity("Core.Features.Specialties.Entities.Speciality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.HasKey("Id");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("Core.Features.Interns.Entities.InternCampaign", b =>
                {
                    b.HasOne("Core.Features.Campaigns.Entities.Campaign", "Campaign")
                        .WithMany("InternIntersections")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Features.Interns.Entities.Intern", "Intern")
                        .WithMany("InternCampaigns")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Features.Specialties.Entities.Speciality", "Speciality")
                        .WithMany("InternIntersections")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Intern");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("Core.Features.Interns.Entities.State", b =>
                {
                    b.HasOne("Core.Features.Interns.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Features.Interns.Entities.InternCampaign", "InternCampaign")
                        .WithMany("States")
                        .HasForeignKey("InternId", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InternCampaign");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Core.Features.Campaigns.Entities.Campaign", b =>
                {
                    b.Navigation("InternIntersections");
                });

            modelBuilder.Entity("Core.Features.Interns.Entities.Intern", b =>
                {
                    b.Navigation("InternCampaigns");
                });

            modelBuilder.Entity("Core.Features.Interns.Entities.InternCampaign", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("Core.Features.Specialties.Entities.Speciality", b =>
                {
                    b.Navigation("InternIntersections");
                });
#pragma warning restore 612, 618
        }
    }
}
